export const typeData = [
  {
    type: "A",
    species: "샴",
    description1: "누구보다 먼저 나서서 의사소통해요.",
    description2: "수다스럽고 다른 고양이들에게 인기가 많아요.",
    description3: "고양이들의 관심 한가운데 있는 것을 즐겨요.",
    matchSpecies: "코숏 턱시도",
    matchType: "J",
  },
  {
    type: "B",
    species: "뱅갈",
    description1: "활발해서 뛰고 점프하며 노는 것을 좋아해요.",
    description2: "언제나 다른 고양이들과 함께 있고 싶어해요.",
    description3: "영리하고 호기심이 많아 모험을 좋아해요.",
    matchSpecies: "먼치킨",
    matchType: "I",
  },
  {
    type: "C",
    species: "봄베이",
    description1: "충성심이 깊고 가족과 친구가 삶의 1순위에요.",
    description2: "애정하는 고양이의 관심과 사랑을 받고싶어해요.",
    description3: "다른 고양이가 위험할 때 먼저 나서는 행동파에요.",
    matchSpecies: "랙돌",
    matchType: "L",
  },
  {
    type: "D",
    species: "메인쿤",
    description1: "다른 고양이들과 수다떠는 것을 좋아해요.",
    description2: "미적 감각이 뛰어나 잦은 그루밍으로 털을 가꿔요.",
    description3: "활기차서 다른 고양이들에게 인기가 많아요.",
    matchSpecies: "페르시안",
    matchType: "K",
  },
  {
    type: "E",
    species: "아비시니안",
    description1: "활동적이고 호기심이 많아 새로운 도전을 즐겨요.",
    description2: "다른 고양이들과 놀 때 먼저 나서는 행동파에요.",
    description3: "카리스마가 있어 고양이들의 리더가 되기도 해요.",
    matchSpecies: "스코티시 폴드",
    matchType: "N",
  },
  {
    type: "F",
    species: "코리안숏헤어(카오스)",
    description1: "개성이 넘치고 뛰어난 예술 감각을 가지고 있어요.",
    description2: "대체로 활발하지만 때로는 혼자만의 공상에 빠져요.",
    description3: "틀에 갇힌 상황을 싫어해서 좋아하는 것을 하고 싶어해요.",
    matchSpecies: "코리안숏헤어(고등어)",
    matchType: "M",
  },
  {
    type: "G",
    species: "코리안숏헤어(삼색)",
    description1: "다른 고양이들을 챙기고 선물을 주는 것에 재미를 느껴요.",
    description2: "다른 고양이들의 의견을 존중하기에 리더가 되기도 해요.",
    description3: "다른 고양이들에게는 관대하지만 본인에게는 엄격해요.",
    matchSpecies: "버만",
    matchType: "P",
  },
  {
    type: "H",
    species: "코리안숏헤어(치즈)",
    description1: "처음 보는 고양이에게도 친근하게 먼저 다가가요.",
    description2: "호기심이 많아 광범위한 관심사에 열정적이에요.",
    description3: "다른 고양이들로부터 본능적으로 리더로 인정받기도 해요.",
    matchSpecies: "러시안블루",
    matchType: "O",
  },
  {
    type: "I",
    species: "먼치킨",
    description1: "나 자신과의 약속은 무조건 지키려고 노력하며 성장해요.",
    description2: "어려운 상황에 처하더라도 인내심으로 버티며 극복해요.",
    description3: "규칙적인 일상을 선호하고 예의바르며 침착해요",
    matchSpecies: "뱅갈",
    matchType: "B",
  },
  {
    type: "J",
    species: "코리안숏헤어(턱시도)",
    description1: "오토바이, 익스트림 스포츠 등의 짜릿한 취미를 좋아해요.",
    description2: "손재주가 좋아서 다른 고양이들의 장난감을 고쳐줘요.",
    description3: "창의적이어서 위기 상황에 본인만의 방법으로 대처해요.",
    matchSpecies: "샴",
    matchType: "A",
  },
  {
    type: "K",
    species: "페르시안",
    description1: "관찰력이 좋아 다른 고양이에게 많은 칭찬을 보냅니다.",
    description2: "다른 고양이에게 나누는 것을 즐깁니다. 심지어 츄르까지요",
    description3: "나눌 줄 아는 고양이기에 주변에서 많은 사랑을 받습니다.",
    matchSpecies: "메인쿤",
    matchType: "D",
  },
  {
    type: "L",
    species: "랙돌",
    description1: "어떤 일이든 열정적으로 빠져들지만 후폭풍에 취약해요.",
    description2: "자신의 열정과 지식을 다른 고양이들에게 아낌없이 나눠요.",
    description3: "열정적인 모습이 멋져서 주변 고양이들에게 인기가 많아요.",
    matchSpecies: "봄베이",
    matchType: "C",
  },
  {
    type: "M",
    species: "코리안숏헤어(고등어)",
    description1: "호기심이 많아 이것저것 배우며 갓생 사는 고양이에요.",
    description2: "어려운 도전에 두려워하지 않고 용기있게 도전합니다.",
    description3: "큰 그림을 그리며 계획을 구상하고 이뤄내려고 노력합니다.",
    matchSpecies: "코리안숏헤어(카오스)",
    matchType: "F",
  },
  {
    type: "N",
    species: "스코티시 폴드",
    description1: "표현은 못 하지만 사실 다른 고양이와 깊은 유대감을 원해요.",
    description2: "상상력이 풍부해서 고양이들에게 새로운 놀이를 알려줘요.",
    description3: "자고 그루밍할 때를 제외하고 관심있는 것에 늘 빠져있어요.",
    matchSpecies: "아비시니안",
    matchType: "E",
  },
  {
    type: "O",
    species: "러시안블루",
    description1: "애정하는 고양이에게 아낌없는 사랑과 좋은 영향을 줘요.",
    description2: "싫어하는 고양이에게도 최대한 중립적으로 행동해요.",
    description3: "통찰력이 뛰어나며 창의력과 독창성을 지녔고 세심해요.",
    matchSpecies: "코리안숏헤어(치즈)",
    matchType: "H",
  },
  {
    type: "P",
    species: "버만",
    description1: "상상력이 풍부해서 몽상 속에서 노는 시간을 즐겨요.",
    description2: "애정하는 고양이에게 많은 사랑을 나누는 것을 좋아해요.",
    description3: "다른 고양이들의 감정에 공감하며 도와주려고 노력해요.",
    matchSpecies: "코리안숏헤어(삼색)",
    matchType: "G",
  },
];
